# Generated by Django 3.2.7 on 2021-11-27 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('customuser', '0002_customuser_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customuser.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnWithUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.FloatField()),
                ('price', models.FloatField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('returned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='returnproduct.return')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customuser.customuser')),
            ],
        ),
    ]
