# Generated by Django 3.2.6 on 2021-12-02 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_customuser_organization'),
        ('bank', '0004_auto_20211201_2007'),
        ('returnproduct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('note', models.TextField(blank=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='return_payment_bank', to='bank.bank')),
                ('returned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='returnproduct.return')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_payment_user', to='customuser.customuser')),
            ],
            options={
                'verbose_name': 'Payments For Return',
            },
        ),
    ]
