# Generated by Django 3.2.6 on 2021-12-03 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_belongs_to'),
        ('returnproduct', '0002_returnpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_customer', to='customer.customer'),
        ),
    ]
