# Generated by Django 3.2.6 on 2022-02-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0005_alter_additionalincomes_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionaloutcomes',
            options={'ordering': ['-datetime']},
        ),
    ]
