# Generated by Django 3.2.7 on 2021-09-30 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customuser', '0002_customuser_organization'),
        ('fromstock', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productwithunit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='productwithunit',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fromstock.productinstock'),
        ),
        migrations.AddField(
            model_name='productwithunit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customuser.customuser'),
        ),
        migrations.AddField(
            model_name='productinstock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customuser.customuser'),
        ),
    ]
