# Generated by Django 3.2.7 on 2021-09-30 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customuser', '0002_customuser_organization'),
        ('tax', '0001_initial'),
        ('invoice', '0001_initial'),
        ('customer', '0002_customer_belongs_to'),
        ('product', '0001_initial'),
        ('bank', '0003_bank_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='soldproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customuser.customuser'),
        ),
        migrations.AddField(
            model_name='returnedproduct',
            name='sold_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.soldproduct'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice_payment_bank', to='bank.bank'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_INVOICE_user', to='customuser.customuser'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_customer', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tax.tax'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_user', to='customuser.customuser'),
        ),
    ]
