# Generated by Django 3.2.6 on 2021-12-01 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20211201_2007'),
        ('organization', '0001_initial'),
        ('customuser', '0002_customuser_organization'),
        ('product_transfer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_debt_org', to='organization.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_debt_user', to='customuser.customuser')),
            ],
            options={
                'verbose_name': 'Organization Debt',
            },
        ),
        migrations.AlterField(
            model_name='transferpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transfer_user', to='customuser.customuser'),
        ),
        migrations.CreateModel(
            name='OrgDebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('note', models.TextField(blank=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bank.bank')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_transfer.orgdebt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_debt_payment_user', to='customuser.customuser')),
            ],
            options={
                'verbose_name': 'Organization Debt Payment',
            },
        ),
    ]
